# Automated Security and Dependency Updates
# https://pyup.io/docs/configuration/

# set the default branch
branch: develop

# update schedule
schedule: every week

# search for requirement files
search: True
